### ISSUE TITLE
More configurations

### ISSUE THREAD

**Issue by danlun** [Deejayfool/hass-shutter-card#1]
It would be great to in some way, like with smaller icon (not so wide) to make this card fit better. If you have 3 shutters it would be much better to e able to combine in some way the look. I tried the vertical stack card but again the icon doesnt fit well if you have eg 3 shutters.

**Comment by anarro** [comment]
And a option for a cover type "window" or "door", it's posible?

**Comment by PierreScerri** [comment]
Awesome card.

I agree with @danlun regarding the size.  I have 11 such shutters.  Even grouping them in 3's is still a bit bulky.  Putting 2 shutters in a horizontal stack does not work well either - the icon overflows.

There seems to be a lot of unused space.

The vertical arrangement of the controls makes more sense to me, since the shutters move vertically not horizontally.

Perhaps the name and position of the shutter could be placed above/below the icon.

It could also be useful to be able to hide the 'title'.

Just an idea:
![Screenshot 2020-06-22 at 12 14 01](https://user-images.githubusercontent.com/34303331/85276913-cf9ad380-b482-11ea-9713-ab133108c522.png)

**Comment by Deejayfool** [comment]
Hello !
Thank you for your feedbacks.

I will update the card to :

1. Hide the title if no title is defined (instead of using the default title "Shutter card")
2. Display the buttons vertically on the left or right of the shutter depending on a configuration set by the user.
3. Display the name of the shutter as well as the pourcentage below or above the shutter depending on a configuration set by the user.
3. Update CSS to correctly fit in horizontal and vertical cards.

Concerning the "door" cover type, I think you mean that you want an other picture ? Actually, I'm not really satisfied of the actual picture for the shutter but I'm not a really good designer :) . So if you are able to design a good shutter for window or door, I'ld be glad to use them.

**Comment by anarro** [comment]
Hello!

We think the current image is very beautiful!

Optional:
1- In the window: show the two "sheets" in the window.
2- At the door: with a single leaf and the "lock"

And if you could add the option option to increase or decrease the size (+ 10%, -20%) ...

Thank you for your great work.
Antoni.

**Comment by danlun** [comment]
Thanks, great feeback!

**Comment by Deejayfool** [comment]
I just published a new version (v1.1.0) that add the features you requested.
The only thing I won't be able to fix is when you use the horizontal card... The place is not large enough to display a good shutter so I don't recommand to use it with the horizontal card. But you can use it in vertical card and it now looks better.

**Comment by PierreScerri** [comment]
Very nice.  Well done

**Comment by anarro** [comment]
Thank you, very very nice too!

**Comment by PierreScerri** [comment]
Tried it on my iPad with 4 instances in a horizontal-stack in Panel mode. Looks great!
![IMG_2239](https://user-images.githubusercontent.com/34303331/85400957-85385600-b559-11ea-87f6-d255e172de37.PNG)
