### ISSUE TITLE
invert_percentage

### ISSUE THREAD

**Issue by kaitomalik** [Deejayfool/hass-shutter-card#17]
Hi, great work.

invert_percentage changes the position of the cover image, not the displayed percentage.
If the shutter is open (100%) and you turn on the invert_percentage option, the shutter will be shown in the card as closed but still 100%.
In my case 0% is open and 100% closed. :)
Thanks

**Comment by Breaveheard** [comment]
For me as well.

**Comment by Deejayfool** [comment]
Hello,
I'm not sure to understand what you want. The percentage which is displayed is the percentage provided by your shutter.
So in your case, if the shutter is closed when it's 100%, then you should see a closed shutter and see the percentage 100% when you set `invert_percentage: true`. Isn't it the case ?

**Comment by Breaveheard** [comment]
Hello,
all that is right and fine. But my shutter is showing 100% in case the shutter is open. As you said I would expect it to be the other way around. So it would be good to have an option to completely invert the signal provided by the shutter. Or even only a part. 

![image](https://user-images.githubusercontent.com/6759133/90541096-6aade200-e182-11ea-9a7a-6ce75516e56a.PNG)

**Comment by Deejayfool** [comment]
So if I understand well, you'ld want a new parameter to also invert the percentage displayed ? Even if it's the opposite of the real value of your shutter ? I don't really understand why this would be needed, because it would add confusion.
Imagine I do that, in your case you'ld see "100%" when it's opened, but the real value would be "0%". So if you want to try in the Developer Tool of Home Assistant, it could add confusion because you could write "100%" while thinking it'ld open the shutter, but instead it'ld close the shutter.

**Comment by Deejayfool** [comment]
No answer since more than 1 month. I close this issue.

**Comment by xcuseulm** [comment]
The problem with this is that there are people where the a complete closed shutter is 100% and a complete opend shutter is 0%.
By inverting the percentage  ("=true") a complete closed shutter is displayed with 100% which is correct. But the image that is shown in this case is a complete opend shutter. inverting percentage should change the view of the percentage and not the image in animation.
