### ISSUE TITLE
Request: Smaller or scalable graphics

### ISSUE THREAD

**Issue by ManCaveMedia** [Deejayfool/hass-shutter-card#6]
Not an issue, but a request:
It would be great if the shutter graphic was just a little smaller, or even scalable, so we can fit 2 next to each other in a horizontal stack. Especially on mobile, to save screen estate.
Right now they are being cut off at the right side.

**Comment by ManCaveMedia** [comment]
Sorry, just noticed this has been requested before...

**Comment by roma777roma** [comment]
please ask me too. I have 9 windows and with these sizes I cannot use this card. Thanks

**Comment by thorschtn** [comment]
You can make the picture narrower so that it fits on the horizontal stack card, just take card-mod and adjust the CSS accordingly:

`entities:
  - entity: cover.eg_bad
  - entity: cover.eg_kueche_1
  - entity: cover.eg_esszi_1
  - entity: cover.eg_wohn
  - entity: cover.eg_gaeste_1
style: |
  ha-card {
    font-size: 11px !IMPORTANT;
  }
  .sc-shutter-label {
    font-size: 15px !IMPORTANT;
  }
  .sc-shutter-top {
    text-align: left !IMPORTANT;
  }
  .card-header {
    font-size: 20px !IMPORTANT;
  }
  .sc-shutter-selector-slide {
    width: 54% !IMPORTANT;
  }
  .sc-shutter-selector-picture {
    background-size: 100px 100% !IMPORTANT;
    background-repeat: no-repeat !IMPORTANT;
  }
  .sc-shutter-selector-picker {
    width: 54% !IMPORTANT;
  }
type: 'custom:shutter-card'`

**Comment by thorschtn** [comment]
> Not an issue, but a request:
> It would be great if the shutter graphic was just a little smaller, or even scalable, so we can fit 2 next to each other in a horizontal stack. Especially on mobile, to save screen estate.
> Right now they are being cut off at the right side.

You can make the picture narrower so that it fits on the horizontal stack card, just take card-mod and adjust the CSS accordingly:

style: | ha-card { font-size: 11px !IMPORTANT; } .sc-shutter-label { font-size: 15px !IMPORTANT; } .sc-shutter-top { text-align: left !IMPORTANT; } .card-header { font-size: 20px !IMPORTANT; } .sc-shutter-selector-slide { width: 54% !IMPORTANT; } .sc-shutter-selector-picture { background-size: 100px 100% !IMPORTANT; background-repeat: no-repeat !IMPORTANT; } .sc-shutter-selector-picker { width: 54% !IMPORTANT; } type: 'custom:shutter-card'

**Comment by thorschtn** [comment]
> Not an issue, but a request:
> It would be great if the shutter graphic was just a little smaller, or even scalable, so we can fit 2 next to each other in a horizontal stack. Especially on mobile, to save screen estate.
> Right now they are being cut off at the right side.

Man CaveMedia, You can make the picture narrower so that it fits on the horizontal stack card, just take card-mod and adjust the CSS accordingly:

`style: | ha-card { font-size: 11px !IMPORTANT; } .sc-shutter-label { font-size: 15px !IMPORTANT; } .sc-shutter-top { text-align: left !IMPORTANT; } .card-header { font-size: 20px !IMPORTANT; } .sc-shutter-selector-slide { width: 54% !IMPORTANT; } .sc-shutter-selector-picture { background-size: 100px 100% !IMPORTANT; background-repeat: no-repeat !IMPORTANT; } .sc-shutter-selector-picker { width: 54% !IMPORTANT; } type: 'custom:shutter-card'`

**Comment by Deejayfool** [comment]
Feature added with Pull Request #69
