### ISSUE TITLE
Request: Movement Feedback

### ISSUE THREAD

**Issue by pedrojreis** [Deejayfool/hass-shutter-card#7]
Hello!

First I want to congratulate for this awesome plugin!
Also this is not any issue but a request to add some sort of visual feedback when the shutters are going up or down on the addon 😁
Also, long press on the sensor "title" could Open the sensor data.

Thanks!

**Comment by LSousa77** [comment]
What a great idea! See the shutther goes up and down on an animation!

**Comment by JavierJMzgz** [comment]
Thank you very much for you work, @Deejayfool. 
This feedback could be very usefull when you touch some shutter card by a mistake in order to be sure which one is moving (it could happen when you are sliding the screen).

> What a great idea! See the shutther goes up and down on an animation!

Maybe an animation is complex to implent. From my point of view, it could be enough changing the side buttons to show the movement of the shutter (e.g. in the same way that HA already does).

**Comment by austwhite** [comment]
This sounds like a great idea and would really look great on the UI

**Comment by pedrojreis** [comment]
It seems that #69 solves this issue. I'll close it.
